#!/bin/bash

#
# @(#) Wrapper for absrename (ensures that  "ab" -> "abab", does not end like abababababababababababababa...)
# Use random string for this purpose
#

absrename $1 _8908789hjk89yhf8y34___
absrename _8908789hjk89yhf8y34___ $2

