#!/bin/bash

#
# @(#) Wrapper for absrename (ensures that  "ab" -> "abab", does not end like abababababababababababababa...)
# Use random string for this purpose
#

absrename $1 gsiddgswdymroikufnmc
absrename gsiddgswdymroikufnmc $2

